import { buildChatPayload } from './lib/format.js';
import { loadSettings } from './lib/settings.js';
import { CHAT_SITES, siteForUrl } from './lib/sites.js';
import { waitForTabComplete } from './lib/tabs.js';
import { getTranscriptViaTab } from './lib/youtube-tab.js';
import { getTranscript, parseVideoId } from './lib/youtube.js';

// YouTube's player API rejects requests whose Origin is chrome-extension://…, so
// present this extension's own requests to it as coming from youtube.com.
const ORIGIN_RULE_ID = 1;

async function ensureOriginRule() {
  await chrome.declarativeNetRequest.updateSessionRules({
    removeRuleIds: [ORIGIN_RULE_ID],
    addRules: [
      {
        id: ORIGIN_RULE_ID,
        priority: 1,
        action: {
          type: 'modifyHeaders',
          requestHeaders: [{ header: 'origin', operation: 'set', value: 'https://www.youtube.com' }],
        },
        condition: {
          urlFilter: '||www.youtube.com/youtubei/',
          initiatorDomains: [chrome.runtime.id],
          resourceTypes: ['xmlhttprequest', 'other'],
        },
      },
    ],
  });
}

// Errors where YouTube itself has answered definitively; anything else is worth a retry via a tab.
const FINAL_ERRORS = new Set(['NO_CAPTIONS', 'UNAVAILABLE']);

async function fetchTranscript(videoId, settings, report) {
  try {
    await ensureOriginRule();
    return await getTranscript(videoId, { preferredLang: settings.preferredLang });
  } catch (err) {
    if (FINAL_ERRORS.has(err.code)) throw err;
    console.warn('Direct transcript fetch failed, falling back to a YouTube tab:', err);
    report('Trying again through YouTube…');
    return await getTranscriptViaTab(videoId, { preferredLang: settings.preferredLang });
  }
}

async function ensureContentScript(tabId) {
  await chrome.scripting.executeScript({ target: { tabId }, files: ['content/chat-inject.js'] });
}

async function toast(tabId, message, kind) {
  try {
    await ensureContentScript(tabId);
    await chrome.tabs.sendMessage(tabId, { type: 'yts:toast', message, kind });
  } catch {
    // The page may not be ready yet (or was closed); the popup still shows the status.
  }
}

/**
 * @param {{url: string, tabId?: number, newChat?: 'chatgpt'|'claude'}} request
 * @param {(text: string) => void} report progress shown in the popup (if still open)
 */
async function summarize(request, report) {
  const videoId = parseVideoId(request.url);
  if (!videoId) throw new Error("That doesn't look like a YouTube video link.");

  const settings = await loadSettings();
  let tabId = request.tabId;
  let site;
  let pageLoaded = Promise.resolve();

  if (request.newChat) {
    // Open the chat right away so it loads while the transcript is fetched.
    site = CHAT_SITES[request.newChat];
    tabId = (await chrome.tabs.create({ url: site.newChatUrl, active: true })).id;
    pageLoaded = waitForTabComplete(tabId, 45_000);
    pageLoaded.catch(() => {}); // awaited below; don't report it as unhandled meanwhile
  } else {
    site = siteForUrl((await chrome.tabs.get(tabId)).url);
    if (!site) throw new Error('Switch to a ChatGPT or Claude tab first.');
    toast(tabId, 'Fetching the YouTube transcript…', 'progress');
  }

  try {
    report('Fetching transcript…');
    const transcript = await fetchTranscript(videoId, settings, report);
    const payload = buildChatPayload(transcript, settings);
    const words = payload.stats.words.toLocaleString('en-US');
    report(`Got ${words} words. Adding to ${site.name}…`);

    await pageLoaded;
    await ensureContentScript(tabId);
    const result = await chrome.tabs.sendMessage(tabId, {
      type: 'yts:insert',
      payload: { ...payload, title: transcript.title, autoSend: settings.autoSend },
    });
    if (!result?.ok) throw new Error(result?.error || `Couldn't add the transcript to ${site.name}.`);

    return {
      title: transcript.title,
      words,
      language: transcript.isAutoGenerated ? `${transcript.language} (auto)` : transcript.language,
      siteName: site.name,
      attached: result.attached,
      sent: result.sent,
    };
  } catch (err) {
    // The popup may already be closed, so surface the failure on the page too.
    toast(tabId, err.message, 'error');
    throw err;
  }
}

chrome.runtime.onConnect.addListener((port) => {
  if (port.name !== 'summarize') return;
  let connected = true;
  port.onDisconnect.addListener(() => (connected = false));
  const send = (msg) => connected && port.postMessage(msg);

  port.onMessage.addListener(async (request) => {
    try {
      const result = await summarize(request, (text) => send({ type: 'progress', text }));
      send({ type: 'done', result });
    } catch (err) {
      console.warn(err);
      send({ type: 'error', message: err.message });
    }
  });
});
