export function formatTimestamp(sec) {
  const s = Math.max(0, Math.floor(sec));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const pad = (n) => String(n).padStart(2, '0');
  return h ? `${h}:${pad(m)}:${pad(s % 60)}` : `${m}:${pad(s % 60)}`;
}

export function formatDuration(sec) {
  if (!sec) return 'unknown length';
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = sec % 60;
  if (h) return `${h} h ${m} min`;
  if (m) return s ? `${m} min ${s} s` : `${m} min`;
  return `${s} s`;
}

const ENDS_SENTENCE = /[.!?…]["'”’)\]]*$/;

/**
 * Merges caption fragments into readable paragraphs. A paragraph closes at the first
 * sentence end after `minSec`, or unconditionally at `maxSec`, which keeps timestamps
 * frequent enough to cite without spending tokens on one per caption line.
 */
export function groupIntoParagraphs(segments, { minSec = 30, maxSec = 60 } = {}) {
  const paragraphs = [];
  let current = null;
  for (const seg of segments) {
    if (current?.texts.at(-1) === seg.text) continue; // "[Music] [Music] [Music]"
    current ??= { start: seg.start, texts: [] };
    current.texts.push(seg.text);
    const elapsed = seg.start - current.start;
    if ((elapsed >= minSec && ENDS_SENTENCE.test(seg.text)) || elapsed >= maxSec) {
      paragraphs.push(current);
      current = null;
    }
  }
  if (current) paragraphs.push(current);
  return paragraphs.map((p) => ({ start: p.start, text: p.texts.join(' ') }));
}

export function countWords(text) {
  return text.split(/\s+/).filter(Boolean).length;
}

export function videoUrl(videoId) {
  return `https://www.youtube.com/watch?v=${videoId}`;
}

export function captionLabel(t) {
  return t.isAutoGenerated ? `${t.language} (auto-generated)` : t.language;
}

export function buildTranscriptFile(t, { timestamps = true, includeDescription = true } = {}) {
  const lines = [
    `Title: ${t.title}`,
    `Channel: ${t.channel}`,
    `URL: ${videoUrl(t.videoId)}`,
    `Length: ${t.durationSec ? formatTimestamp(t.durationSec) : 'unknown'}`,
    `Captions: ${captionLabel(t)}`,
  ];

  const description = t.description.trim();
  if (includeDescription && description) {
    lines.push('', '=== DESCRIPTION ===', description);
  }

  lines.push('', timestamps ? '=== TRANSCRIPT (timestamps are [m:ss]) ===' : '=== TRANSCRIPT ===');
  for (const p of groupIntoParagraphs(t.segments)) {
    lines.push('', timestamps ? `[${formatTimestamp(p.start)}] ${p.text}` : p.text);
  }
  return `${lines.join('\n')}\n`;
}

export function makeFileName(title) {
  const base = title
    .replace(/[^\p{L}\p{N}\s\-_.,()'&]/gu, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 60)
    .trim();
  return base ? `${base} - transcript.txt` : 'youtube-transcript.txt';
}

export function fillTemplate(template, vars) {
  return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (match, key) => vars[key] ?? match);
}

/**
 * Builds what gets put into the chat: the prompt plus either a .txt attachment or,
 * in inline mode, transcript text to paste after the prompt. The two are pasted
 * separately because Claude turns long pastes into an attachment, and the prompt
 * should stay in the message box either way.
 */
export function buildChatPayload(t, settings) {
  const fileText = buildTranscriptFile(t, settings);
  const fileName = makeFileName(t.title);
  const asFile = settings.delivery !== 'inline';

  const vars = {
    title: t.title,
    channel: t.channel,
    url: videoUrl(t.videoId),
    duration: formatDuration(t.durationSec),
    language: captionLabel(t),
  };
  const inlineWhere = 'pasted at the end of this message';
  const prompt = fillTemplate(settings.promptTemplate, {
    ...vars,
    where: asFile ? `in the attached file "${fileName}"` : inlineWhere,
  }).trim();

  return {
    prompt,
    // Used if the page won't accept the file and the transcript has to be pasted instead.
    fallbackPrompt: fillTemplate(settings.promptTemplate, { ...vars, where: inlineWhere }).trim(),
    file: asFile ? { name: fileName, content: fileText } : null,
    inlineTranscript: asFile ? null : `----- TRANSCRIPT -----\n\n${fileText}`,
    stats: { words: countWords(t.segments.map((s) => s.text).join(' ')), chars: fileText.length },
  };
}
